version: '3'

services:
  api:
    build: ./api
    command: npm run start:dev
    restart: unless-stopped
    volumes:
      - ./api/src:/app/src
    env_file:
      - ./api/.env
    depends_on:
      - postgres-auth

  postgres-auth:
    image: postgres:13.4
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - ./postgres/.env
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5400:5432"

  nginx:
    image: nginx:stable-alpine
    ports:
    - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - auth-api
