name: CI
# Controls when the workflow will run
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            # Set env variables
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export ACCESS_KEY=${{ secrets.ACCESS_KEY }}
            export SECRET_KEY=${{ secrets.SECRET_KEY }}
            
            # Stop running container
            docker stop $(echo $CONTAINER_NAME)
            # Remove old container
            docker rm $(echo $CONTAINER_NAME)
            # Run a new container from a new image
            docker run --env-file $(echo $ENV_FILE_PATH) \
            -v $(echo $LOGS_PATH):/logs -d \
            --restart always \
            --publish 8000:8000 \
            --name $(echo $CONTAINER_NAME) \
            --link=jewerly-db:db \
            $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
