name: CI
# Controls when the workflow will run
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Set env variables
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export ACCESS_KEY=${{ secrets.ACCESS_KEY }}
            export SECRET_KEY=${{ secrets.SECRET_KEY }}
            
            # Stop running container
            docker kill $(docker ps -q)
            # Remove old container
            docker rm $(docker ps -a -q)
            # Remove old images
            docker rmi $(docker images -q)
            # Change directory
            cd app
            # Clone repo 
            git clone https://github.com/YuriiDzyuba/secret.git
            # run docker- compose 
            docker-compose up --build
           
